# Generated by Django 4.2.2 on 2023-06-25 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0086_alter_site_root_page"),
        ("wagtailimages", "0026_image_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_%(class)s",
                to="wagtailcore.site",
            ),
        ),
    ]
