# Generated by Django 4.1.3 on 2022-12-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("wagtailcore", "0078_referenceindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="permission_sitegroups",
                        to="auth.permission",
                        verbose_name="permissions",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_sitegroups",
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
            },
        ),
        migrations.AddConstraint(
            model_name="sitegroup",
            constraint=models.UniqueConstraint(
                fields=("name", "site"), name="unique_name_site"
            ),
        ),
    ]
