# Generated by Django 4.1.3 on 2022-12-05 13:16

from django.db import migrations


def initiate_site_group_with_group_data(apps, schema_editor):
    Group = apps.get_model("auth.Group")
    Site = apps.get_model("wagtailcore.Site")
    SiteGroup = apps.get_model("wagtailcore.SiteGroup")
    for group in Group.objects.all():
        for site in Site.objects.all():
            if Site.objects.all().count() > 1:
                obj = SiteGroup.objects.create(id=group.id, name=group.name, site=site)
            else:
                obj = SiteGroup.objects.create(name=group.name, site=site)
            obj.permissions.set(group.permissions.all())
            obj.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0079_sitegroup_sitegroup_unique_name_site"),
    ]

    operations = [
        migrations.RunPython(
            initiate_site_group_with_group_data,
            do_nothing,
        )
    ]
