# Generated by Django 4.1.3 on 2022-12-05 13:16

from django.db import migrations


def initiate_site_group_with_group_data(apps, schema_editor):
    Group = apps.get_model("auth.Group")
    Site = apps.get_model("wagtailcore.Site")
    SiteGroup = apps.get_model("wagtailcore.SiteGroup")

    default_site = Site.objects.filter(is_default_site=True).first()
    for group in Group.objects.all():
        obj = SiteGroup.objects.create(id=group.id, name=group.name, site=default_site)
        obj.permissions.set(group.permissions.all())
        obj.save()


def flush_site_group_records(apps, schema_editor):
    SiteGroup = apps.get_model("wagtailcore.SiteGroup")
    SiteGroup.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0079_sitegroup_sitegroup_unique_name_site"),
    ]

    operations = [
        migrations.RunPython(
            initiate_site_group_with_group_data,
            flush_site_group_records,
        )
    ]
