# Generated by Django 4.1.3 on 2022-12-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0080_replace_group_records_with_sitegroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionviewrestriction",
            name="groups",
            field=models.ManyToManyField(
                blank=True, to="wagtailcore.sitegroup", verbose_name="groups"
            ),
        ),
        migrations.AlterField(
            model_name="groupapprovaltask",
            name="groups",
            field=models.ManyToManyField(
                help_text="Pages at this step in a workflow will be moderated or approved by these groups of users",
                to="wagtailcore.sitegroup",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="grouppagepermission",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_permissions",
                to="wagtailcore.sitegroup",
                verbose_name="group",
            ),
        ),
        migrations.AlterField(
            model_name="pageviewrestriction",
            name="groups",
            field=models.ManyToManyField(
                blank=True, to="wagtailcore.sitegroup", verbose_name="groups"
            ),
        ),
    ]
