# Generated by Django 4.1.5 on 2023-03-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0081_alter_collectionviewrestriction_groups_and_more"),
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = []
