# Generated by Django 4.2.1 on 2023-05-08 14:08

import uuid

import django.core.validators
from django.db import migrations, models
from django.utils.text import slugify
import django.utils.timezone


def random_default(n):
    return str(uuid.uuid4())[-n:-1]


def populate_sitename(apps, schema_editor):
    Site = apps.get_model("wagtailcore.Site")

    for s in Site.objects.all():
        s.sitename = slugify(s.site_name) if s.site_name else random_default(10)
        s.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0084_merge_20230305_1030"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="is_default_site",
        ),
        migrations.AddField(
            model_name="site",
            name="sitename",
            field=models.SlugField(
                help_text="The username for the site.",
                max_length=31,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(5)],
                verbose_name="sitename",
            ),
        ),
        migrations.RunPython(populate_sitename, do_nothing),
        migrations.AlterField(
            model_name="site",
            name="sitename",
            field=models.SlugField(
                help_text="The username for the site.",
                max_length=31,
                null=False,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(5)],
                verbose_name="sitename",
            ),
        ),
    ]
