# Generated by Django 4.2.1 on 2023-05-13 09:11

from django.db import migrations, models
import django.db.models.deletion
from wagtail.models import Page


def set_root_for_rootpage(apps, schema_editor):
    Site = apps.get_model("wagtailcore.Site")

    for s in Site.objects.all():
        s.root_page_id = Page.objects.get(pk=s.root_page.pk).get_root().id
        s.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "wagtailcore",
            "0085_remove_site_is_default_site_remove_site_site_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="root_page",
            field=models.ForeignKey(
                limit_choices_to={"depth": 1},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sites_rooted_here",
                to="wagtailcore.page",
                verbose_name="root page",
            ),
        ),
        migrations.RunPython(set_root_for_rootpage, do_nothing),
    ]
